services:

  redis:
    image: redis:7-alpine

    restart: unless-stopped

    ports:
      - "6379:6379"


  livekit:
    image: livekit/livekit-server:latest

    restart: unless-stopped

    command:
      - "--config"
      - "/etc/livekit.yaml"

    volumes:
      - ./livekit.yaml:/etc/livekit.yaml

    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"

    depends_on:
      - redis


  egress:
    image: livekit/egress:latest

    restart: unless-stopped

    environment:
      EGRESS_CONFIG_FILE: /etc/egress.yaml

    volumes:
      - ./egress.yaml:/etc/egress.yaml

    depends_on:
      - redis
      - livekit
